project:
  # This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name
  machine_name: 'bolted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'Bolted 8'
  profile:
    name: 'lightning'
    # Please ensure contrib profiles are also in your composer.json file.
    contrib: true
  # This is used to build front end artifacts. E.g., SASS compilation.
  themes:
    - thunder
  # These are random strings used to configure the hash salt.
  hash_salt: ${project.hash_salt}

# Configuration settings for new git repository.
git:
  default_branch: master
  remotes:
    # Defining git remotes allows builds deployed via CI.
    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git

drush:
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self

# Hosting environment flags.
# Examples: acsf (Acquia Cloud Site Factory), ac (Acquia Cloud)
# hosting: "acsf"
# hosting: "ac"
