project:
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'blted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'BLTed 8'
  profile:
    # You can generate a custom profile by running '../vendor/bin/drupal generate:profile' from the docroot.
    name: 'lightning'
    # Please ensure contrib profiles are also in your composer.json file.
    contrib: true
  # This will be used as the local uri for all developers.
  local:
    protocol: http
    hostname: ${project.machine_name}.localhost

# Configuration settings for new git repository.
git:
  default_branch: master
  remotes:
    # Defining git remotes allows builds deployed via CI.
    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git
    # - radass4@svn-11692.prod.hosting.acquia.com:radass4.git

drush:
  # You can set custom project aliases in drush/site-aliases/aliases.drushrc.php.
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${project.machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self
    # The drush alias against which all ci commands are run.
    ci: self
    # The default drush alias to be used when no environment is specified.
  default_alias: ${drush.aliases.local}

# Custom tasks that are triggered at pre-defined times in the build process.
# The tasks hook into BLT's existing Phing targets. Available hooks keys are:
# frontend-build, post-deploy-build, and post-setup-build.
target-hooks:
  # Executed when front end dependencies should be installed.
  frontend-setup:
    # E.g., ${docroot}/sites/all/themes/custom/mytheme.
    dir: ${docroot}
    # E.g., `npm install` or `bower install`.
    command: echo 'No frontend setup configured.'
  # Executed when front end assets should be generated.
  frontend-build:
    # E.g., ${docroot}/sites/all/themes/custom/mytheme.
    dir: ${docroot}
    # E.g., `npm run build`.
    command: echo 'No frontend build configured.'
  # Executed after deployment artifact is created.
  post-deploy-build:
    dir: ${deploy.dir}/docroot/profiles/contrib/lightning
    command: npm run install-libraries
  # Executed after setup:build is run.
  post-setup-build:
    dir: ${docroot}/profiles/contrib/lightning
    command: npm run install-libraries

# Define any custom Phing files that you'd like to import. E.g., ${repo.root}/blt/phing/build.xml
import: ~

# Hosting environment flags.
# Examples: acsf (Acquia Cloud Site Factory), ac (Acquia Cloud)
# hosting: "acsf"
# hosting: "ac"
