project:
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'bolted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'Bolted 8'
  profile:
    name: 'lightning'
    # Please ensure contrib profiles are also in your composer.json file.
    contrib: true
  # This is used to build front end artifacts. E.g., SASS compilation.
  themes:
    - thunder
  # These are random strings used to configure the hash salt.
  hash_salt: ${project.hash_salt}

drush:
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self

# Defaults for git configuration
# Note: this is only used in `./bolt.sh create`
git:
  default_branch: develop

# Define deployment environments, and git repositories here.
# Defining git remotes allows builds to deployed via CI.
# Defining hosting allows certain artifacts to be deployed for different hosts

deployments:
  - default
  # - acsf

default:
  #hosting: aws
  name: Default deployment environment
  gits:
    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git

# Below is an example of another deployment target
#acsf:
#  hosting: acsf
#  gits:
#    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git
#    - bolt@bolt-example.com:bolt8.git
#  name: Profserv ACSF
