project:
  # The project's composer.json will be updated with the below vendor_name and description
  # and should be updated directly to change these values after initial creation.
  vendor_name: 'acquia'
  description: 'A short description of the package. Usually this is just one line long.'
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'blted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'BLTed 8'
  profile:
    name: 'lightning'
    # Please ensure contrib profiles are also in your composer.json file.
    contrib: true
  # This is used to build front end artifacts. E.g., SASS compilation.
  themes:
    - thunder
  # These are random strings used to configure the hash salt.
  hash_salt: ${project.hash_salt}
  # This will be used as the local uri for all developers.
  local:
    protocol: http
    hostname: ${project.machine_name}.localhost

# Configuration settings for new git repository.
git:
  default_branch: master
  remotes:
    # Defining git remotes allows builds deployed via CI.
    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git

drush:
  # You can set custom project aliases in drush/site-aliases/aliases.drushrc.php.
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${project.machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self
    # The drush alias against which all ci commands are run.
    ci: self
    # The default drush alias to be used when no environment is specified.
  default_alias: ${drush.aliases.local}

# Custom tasks that are triggered at pre-defined times in the build process.
# The tasks hook into BLT's existing Phing targets. Available hooks keys are:
# frontend-build, post-deploy-build, and post-setup-build.
target-hooks:
  # Executed when front end assets should be generated.
  frontend-build:
    # E.g., ${docroot}/sites/all/themes/custom/mytheme.
    dir: ${docroot}
    # E.g., `npm install` or `bower install`.
    command: echo 'No frontend build configured.'
  # Executed after deployment artifact is created.
  post-deploy-build:
    dir: ${deploy.dir}/docroot/profiles/contrib/lightning
    command: npm install && bower install
  # Executed after setup:build is run.
  post-setup-build:
    dir: ${docroot}/profiles/contrib/lightning
    command: npm run install-libraries

# Hosting environment flags.
# Examples: acsf (Acquia Cloud Site Factory), ac (Acquia Cloud)
# hosting: "acsf"
# hosting: "ac"
