#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )
PHPCS_BIN=vendor/bin/phpcs

if [ ! -f $PHPCS_BIN ]; then
  echo "PHP Code Sniffer was not found in this project's bin directory. Please run composer install. "
  exit 1
fi

${ROOT_DIR}/vendor/bin/blt git:precommit -Dfiles="$LIST" -q
exit 0;
