#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )
PHPCS_BIN=vendor/bin/phpcs

if [ ! -f $PHPCS_BIN ];
  then
    echo "PHP Code Sniffer was not found in this project's bin directory. Please run composer install. "
    exit 1
fi

echo "Sniffing staged files via PHP Code Sniffer..."
${ROOT_DIR}/vendor/bin/blt validate:phpcs:files -Dfiles="$LIST" -silent -emacs || exit 1;
echo "Linting custom twig files..."
${ROOT_DIR}/vendor/bin/blt validate:twig -silent -emacs || exit 1;
echo "Validating composer.json..."
composer validate --quiet --no-check-all || (echo 'composer.json is not valid. Run `composer validate` for more information.' && exit 1;)
echo "Ok!"

# Return the status of the last run command.
exit $?
