<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * An example global include file.
 *
 * To use this file, rename to global.settings.php.
 */

/**
 * Include all settings files in docroot/sites/settings.
 *
 * Any file placed directly in the docroot/sites/settings directory whose name
 * matches a glob pattern of *.settings.php will be incorporated to the settings
 * of every defined site.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
if ($settings_files = preg_grep('/global.settings.php/', glob(DRUPAL_ROOT . "/sites/settings/*.settings.php"), PREG_GREP_INVERT)) {
  foreach ($settings_files as $settings_file) {
    require $settings_file;
  }
}
