<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * Any file placed directly in the docroot/sites/settings directory whose name
 * matches a glob pattern of *.settings.php will be incorporated to the settings
 * of every defined site.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 *
 */
