#!/bin/bash -e

GIT_ROOT=$(git rev-parse --show-toplevel)
BOLT_BRANCH=8.x

# Upstream directories to pull. These will be prefixed with "template/".
BOLT_DIRS=(
  "blt.sh"
  "build/core"
  "drush.wrapper"
  "factory-hooks/post-settings-php/protect_env.php.example"
  "factory-hooks/pre-settings-php/includes.php.example"
  "hooks/samples"
  "hooks/templates"
  "scripts/blt"
  "scripts/deploy"
  "scripts/drupal"
  "scripts/git-hooks/pre-commit"
  "scripts/release-notes"
)

# Move into repository root.
cd $GIT_ROOT

echo "Copying down upstream changes to the BLT template."

# Iteratively pull down upstream directories.
for i in "${BOLT_DIRS[@]}"
  do
    svn export https://github.com/acquia/blt/branches/$BOLT_BRANCH/template/$i $i --force
done

# Restore execute permissions.
chmod 755 blt.sh
chmod 755 drush.wrapper

echo "Changes have been pulled down. Please review and commit desired changes."
