project:
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'blted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'BLTed 8'
  profile:
    name: 'lightning'
  # This will be used as the local uri for all developers.
  local:
    protocol: http
    hostname: local.${project.machine_name}.com

# Configuration settings for new git repository.
git:
  default_branch: master
  remotes: []

drush:
  # You can set custom project aliases in drush/site-aliases/aliases.drushrc.php.
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${project.machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self
    # The drush alias against which all ci commands are run.
    ci: self
    # The default drush alias to be used when no environment is specified.
  default_alias: ${drush.aliases.local}

# Configuration management options, such as core CM or features.
# cm:
#   features:
#     bundle:
#       - blted8
#     no-overrides: 'true'

# An array of modules to be enabled or uninstalled automatically in local, ci, and deploy contexts.
modules:
  local:
    enable:
      - dblog
      - devel
      - seckit
      - views_ui
    uninstall:
      - acsf
      - acquia_connector
      - shield
  ci:
    enable: []
    uninstall:
      - acquia_connector
      - shield
  dev:
    enable:
      - acquia_connector
      - shield
    uninstall: []
  test:
    enable:
      - acquia_connector
      - shield
    uninstall:
      - devel
      - views_ui
  prod:
    enable:
      - acquia_connector
      - shield
    uninstall:
      - devel
      - views_ui
