project:
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  machine_name: 'blted8'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'BLT'
  human_name: 'BLTed 8'
  profile:
    # You can generate a custom profile by running '../vendor/bin/drupal generate:profile' from the docroot.
    name: 'lightning'
  # This will be used as the local uri for all developers.
  local:
    protocol: http
    hostname: local.${project.machine_name}.com
  # These values will be used to generate the theme for this project.
  subtheme:
    machine_name: cogsub
    human_name: 'Cog Subtheme'
    description: 'A subtheme of Cog.'

# Configuration settings for new git repository.
git:
  default_branch: master
  remotes:
    # Defining git remotes allows builds deployed via CI.
    - bolt8@svn-5223.devcloud.hosting.acquia.com:bolt8.git

drush:
  # You can set custom project aliases in drush/site-aliases/aliases.drushrc.php.
  aliases:
    # The remote environment from which the database will be pulled.
    remote: ${project.machine_name}.test
    # The local environment against which all local drush commands are run.
    local: self
    # The drush alias against which all ci commands are run.
    ci: self
    # The default drush alias to be used when no environment is specified.
  default_alias: ${drush.aliases.local}

# Custom tasks that are triggered at pre-defined times in the build process.
# The tasks hook into BLT's existing Phing targets. Available hooks keys are:
# frontend-build, post-deploy-build, and post-setup-build.
target-hooks:
  # Executed when front end dependencies should be installed.
  frontend-setup:
    # E.g., ${docroot}/sites/all/themes/custom/mytheme.
    dir: '${docroot}/themes/custom/${project.subtheme.machine_name}'
    # E.g., `npm install` or `bower install`.
    command: 'yarn install; npm run build'
  # Executed when front end assets should be generated.
  frontend-build:
    # E.g., ${docroot}/sites/all/themes/custom/mytheme.
    dir: '${docroot}/themes/custom/${project.subtheme.machine_name}'
    # E.g., `npm run build`.
    command: 'gulp'
  # Executed after deployment artifact is created.
  post-deploy-build:
    dir: ${docroot}
    command: echo 'No post-deploy build configured.'
  # Executed after setup:build is run.
  post-setup-build:
    dir: ${docroot}
    command: echo 'No post-setup build configured.'

# Configuration management options, such as core CM or features.
# cm:
#   features:
#     bundle: blted8

# Define any custom Phing files that you'd like to import. E.g., ${repo.root}/blt/phing/build.xml
import: ~

# An array of modules to be enabled or uninstalled automatically in local, ci, and deploy contexts.
modules:
  local:
    enable:
      - dblog
      - devel
      - field_ui
      - seckit
      - views_ui
    uninstall:
      - acsf
      - acquia_connector
      - shield
  ci:
    enable: []
    uninstall:
      - acquia_connector
      - shield
  dev:
    enable:
      - acquia_connector
      - shield
    uninstall: []
  test:
    enable:
      - acquia_connector
      - shield
    uninstall:
      - devel
      - field_ui
      - views_ui
  prod:
    enable:
      - acquia_connector
      - shield
    uninstall:
      - devel
      - field_ui
      - views_ui
