# Values in this file may override default values set elsewhere.

behat:
  # @see http://docs.behat.org/en/v2.5/guides/6.cli.html#gherkin-filters
  # When tests:behat:run target is executed, these tags will be passed to Behat.
  tags: ~@example-multisite
  # When tests:behat:run target is executed, this Behat profile will be used.
  # @see tests/behat/example.local.yml for Behat profile definition.
  profile: example-multisite

tests:
  # This is used for ad-hoc creation of a server via `drush rs` during CI.
  # This needs to match a site entry in docroot/sites/sites.php, and should
  # be assigned as the base_url in a corresponding Behat profile in
  # tests/behat/example.local.yml.
  server:
    port: 8888
    url: http://127.0.0.1:${tests.server.port}

project:
  profile:
    name: example_multisite_profile

# Drush aliases to be used for syncs and setups.
drush:
  aliases:
    local: mysite.local
    remote: mysite.test

# If you would like to manage configuration for this multisite
# completely separately from the default site, change this value to
# ${cm.core.path}/site2. Be sure to also set
# $config_directories['sync'] = $dir . "/config/site2" in settings.php
# for the site.
# cm.core.dirs.sync.path: ${cm.core.path}/default
