# @file default.yml
# Site definition file for the default site.
aliases:
  local: self
  remote: default.dev
  ci: self
uri:
  local: default.local
  ci: 127.0.0.1:8888
  dev: defaultdev.prod.acquia-sites.com
  test: defaultstg.prod.acquia-sites.com
  prod: default.com
