behat:
  config: ${repo.root}/tests/behat/local.yml
  haltonerror: true
  strict: true
  profile: local
  # If true, `drush runserver` will be used for executing tests.
  run-server: false
  # This is used for ad-hoc creation of a server via `drush runserver`.
  server-url: http://127.0.0.1:8888
  # If true, Selenium standalone server will be launched with Behat.
  launch-selenium: true
  # If true, PhantomJS GhostDriver will be launched with Behat.
  launch-phantomjs: false
  # An array of paths with behat tests that should be executed.
  paths:
    # - ${docroot}/modules
    # - ${docroot}/profiles
    - ${repo.root}/tests/behat
  tags: '~ajax&&~experimental&&~lightningextension'
  verbose: ${blt.verbose}
  extra: ''

bin.path: vendor/bin

blt:
  update:
    ignore-existing-file: ${blt.root}/scripts/blt/ignore-existing.txt
  # Default verbosity level for <exec> tasks. If Phing msg level is => than info, this will be set to info.
  exec_level: verbose
  # If Phing verbosity is flagged, this will be changed to true. Affects verbosity of tasks like Drush, Behat.
  verbose: false
  config-files:
    project: ${repo.root}/blt/project.yml
    local: ${repo.root}/blt/project.local.yml
    example-local: ${repo.root}/blt/example.project.local.yml
    schema-version: ${repo.root}/blt/.schema_version
    multisite: ${docroot}/sites/${multisite.name}/site.yml

composer:
  bin: ${repo.root}/${bin.path}

cm:
  # Possible values: core-only, config-split, features, none.
  strategy: config-split
  core:
    # The parent directory for configuration directories, relative to the docroot.
    path: ../config
    # The default config key to use for imports. This is the key used in Drupal's global $config_directories variable.
    # E.g., $config_directories['sync']. It must have a corresponding key in cm.core.dirs. E.g., `cm.core.dirs.sync`.
    key: sync
    # A different config key is used by the deploy:update step, which is executed on Acquia Cloud.
    deploy-key: vcs
    dirs:
      # Corresponding values are defined in default.local.settings.php.
      sync:
        path: ${cm.core.path}/default
  features:
    no-overrides: true

deploy:
  # If true, dependencies will be built during deploy. If false, you should commit dependencies directly.
  build-dependencies: true
  dir: ${repo.root}/deploy
  exclude_file: ${blt.root}/phing/files/deploy-exclude.txt
  exclude_additions_file: ${repo.root}/blt/deploy-exclude-additions.txt
  gitignore_file: ${blt.root}/phing/files/.gitignore
  git:
    # If true, deploys will fail if there are uncommitted changes.
    failOnDirty: true

# File and Directory locations.
docroot.relative: ${repo.root.relative}/docroot
docroot: ${repo.root}/docroot

# Drupal Account Credentials. These are used for installing Drupal.
drupal:
  account.name: admin
  account.password: admin
  account.mail: no-reply@acquia.com
  locale: en
  local_settings_file: ${docroot}/sites/default/settings/local.settings.php
  settings_file: ${docroot}/sites/default/settings.php

drush:
  bin: ${composer.bin}/drush
  cmd: ${drush.bin} @${drush.alias} -l default
  dir: ${docroot}
  uri: default
  assume: yes
  passthru: yes
  logoutput: yes
  sanitize: true
  verbose: ${blt.verbose}

git:
  # The value of a hook should be the file path to a directory containing an
  # executable file named after the hook.
  # Changing a hook value to 'false' will disable it.
  hooks:
    pre-commit: ${blt.root}/scripts/git-hooks
    commit-msg: ${blt.root}/scripts/git-hooks

# You may provide a list of sites for BLT to run commands against,
# otherwise BLT will generate this sites list based on directories
# in ${docroot}/sites/*/
#
# multisite:
#  name:
#    - default

reports:
  localDir: ${repo.root}/reports
  remoteDir: reports

phpcs:
  filesets:
    - files.php.custom.modules
    - files.php.tests
    - files.php.custom.themes
    - files.frontend.custom.themes
  haltonerror: true
  haltonwarning: true

phpcbf:
  filesets:
    - files.php.custom.modules
    - files.php.tests
    - files.php.custom.themes
    - files.frontend.custom.themes

project:
  local:
    uri: ${project.local.protocol}://${project.local.hostname}

sync:
  # By default, files are not synced during local:sync.
  # Set this value to 'true' or pass -Dsync.files=true
  # to override this behavior.
  files: false
