behat:
  config: ${repo.root}/tests/behat/local.yml
  profile: local
  # If true, `drush runserver` will be used for executing tests.
  run-server: false
  # This is used for ad-hoc creation of a server via `drush runserver`.
  server-url: http://127.0.0.1:8888
  # If true, PhantomJS GhostDriver will be launched with Behat.
  launch-phantom: true
  # An array of paths with behat tests that should be executed.
  paths:
    # - ${docroot}/modules
    # - ${docroot}/profiles
    - ${repo.root}/tests/behat
  tags: '~ajax'
  verbose: ${blt.verbose}

blt:
  update:
    ignore-existing-file: ${blt.root}/scripts/blt/ignore-existing.txt
  # Default verbosity level for <exec> tasks.
  exec_level: verbose
  # If blt.level >= info, this will be changed to true. Affects verbosity of tasks like Drush, Behat.
  verbose: false
  # From most to least verbose: debug, verbose, info, warn, error.
  # Equivalent of using Phing arguments -debug, -verbose, [none], -quiet, -silent
  # Note that this does not affect passthru output.
  level: info

composer:
  bin: ${repo.root}/vendor/bin

deploy:
  # If true, dependencies will be built during deploy. If false, you should commit dependencies directly.
  build-dependencies: true
  dir: ${repo.root}/deploy
  exclude_file: ${blt.root}/phing/files/deploy-exclude.txt
  gitignore_file: ${blt.root}/phing/files/.gitignore

# File and Directory locations.
docroot.relative: ${repo.root.relative}/docroot
docroot: ${repo.root}/docroot

# Drupal Account Credentials. These are used for installing Drupal.
drupal:
  account.name: admin
  account.password: admin
  account.mail: no-reply@acquia.com

drush:
  bin: ${composer.bin}/drush
  cmd: ${drush.bin} @${drush.alias} -r ${docroot} -l ${multisite.name}
  dir: ${docroot}
  uri: ${multisite.name}
  assume: yes
  passthru: yes
  verbose: ${blt.verbose}

multisite:
  # The docroot/sites/default directory is used by default.
  name: default

reports:
  localDir: ${repo.root}/reports
  remoteDir: reports

phpcs:
  filesets:
    - files.php.custom.modules
    - files.php.tests
    - files.frontend.custom.themes

project:
  local:
    uri: ${project.local.protocol}://${project.local.hostname}
