#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )
PHPCS_BIN=vendor/bin/phpcs

if [ ! -f $PHPCS_BIN ];
  then
    echo "PHP Code Sniffer was not found in this project's bin directory. Please run composer install. "
  else
    echo "Sniffing staged files via PHP Code Sniffer."
fi

for FILE in $LIST
do
    ${ROOT_DIR}bolt.sh validate:phpcs:file -Dfile=$FILE -q
done
exit 0;
