---
assets:
  - deploy_key
  - db.sql.gz
insecureStashDownload: true

steps:
  - name: Install deploy key
    plugin: Script
    script: |
      mkdir -p ~/.ssh
      cp $ASSET_DIR/deploy_key ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

  - name: 'Before install'
    plugin: Script
    script:
     - cd $SRC_DIR
     - "$SRC_DIR/blt/files/probo/setup_environment"
     - composer self-update
     - composer validate --no-check-all --ansi
     - composer install
     - composer run-script blt-alias

  - name: 'Import Drupal assets'
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    database: db.sql.gz
    databaseGzipped: true
    configSyncDirectory: '../config/default'

  - name: 'Setup project'
    plugin: Script
    script:
     - "$SRC_DIR/blt/files/probo/setup_project"

  - name: 'Run tests'
    plugin: Script
    script:
     - "$SRC_DIR/blt/files/probo/run_tests"

  - name: 'Deploy'
    plugin: Script
    script:
     - "$SRC_DIR/blt/files/probo/deploy_branch"
