---
image: proboci/ubuntu-14.04-lamp:php-5.6
steps:
  - name: 'Before install'
    plugin: Script
    script:
     - cd $SRC_DIR
     - "PHP_VERSION='5.6' source scripts/probo/setup_environment"
     - composer self-update
     - composer validate --no-check-all --ansi
     - composer install --ansi
     - composer run-script blt-alias

  - name: 'Setup project'
    plugin: Script
    script:
     - "source $SRC_DIR/vendor/acquia/blt/scripts/probo/setup_project"

  - name: 'Run tests'
    plugin: Script
    script:
     - "source $SRC_DIR/vendor/acquia/blt/scripts/probo/run_tests"

  - name: 'Deploy'
    plugin: Script
    script:
     - "source $SRC_DIR/vendor/acquia/blt/scripts/probo/deploy_branch"
