---
image: proboci/ubuntu-14.04-lamp:php-5.6
steps:
  - name: 'Before install'
    plugin: Script
    script:
     - cd $SRC_DIR
     - "PHP_VERSION='5.6' scripts/probo/setup_environment"
     - composer self-update
     - composer validate --no-check-all --ansi
     - composer install
     - composer run-script blt-alias

  - name: 'Install Drupal'
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    profileName: lightning
    runInstall: true
    installArgs: "--config-dir=../config/default"
    configSyncDirectory: '../config/default'

  - name: 'Setup project'
    plugin: Script
    script:
     - "$SRC_DIR/vendor/acquia/blt/scripts/probo/setup_project"

  - name: 'Run tests'
    plugin: Script
    script:
     - "$SRC_DIR/vendor/acquia/blt/scripts/probo/run_tests"

  - name: 'Deploy'
    plugin: Script
    script:
     - "$SRC_DIR/vendor/acquia/blt/scripts/probo/deploy_branch"
