#!/usr/bin/env bash

set -ev

# Add the git remote to known hosts
$SRC_DIR/vendor/bin/yaml-cli get:value blt/blt.yml git.remotes | cut -d@ -f2 | cut -d: -f1 >> ~/.ssh/known_hosts

$SRC_DIR/vendor/bin/blt artifact:deploy --commit-msg "Automated commit by Probo CI for Build ${BUILD_ID}" --branch "${BRANCH_NAME}-build" --ignore-dirty --no-interaction --verbose

set +v
