#!/usr/bin/env bash

set -ev

PHP_VERSION=${PHP_VERSION:-"5.6"}

export PATH="${SRC_DIR}/vendor/bin":$PATH

# Install Node v6.
sudo npm install -g n
sudo n lts
npm install -g gulp-cli
npm install -g bower

# Install chrome.
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update
sudo apt-get -y install google-chrome-stable

# Create fake mailer.
ln -s /bin/true /usr/sbin/sendmail
echo 'max_execution_time = 120' >> /etc/php/${PHP_VERSION}/cli/conf.d/probo.ini
echo 'sendmail_path = /bin/true' >> /etc/php/${PHP_VERSION}/cli/conf.d/probo.ini

# Enable $_ENV variables in PHP.
echo 'variables_order = "EGPCS"' >> /etc/php/${PHP_VERSION}/cli/conf.d/probo.ini
# Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
echo "always_populate_raw_post_data = -1" >> /etc/php/${PHP_VERSION}/cli/conf.d/probo.ini
# Set PHP memory limit to something more realistic.
echo "memory_limit=512M" >> /etc/php/${PHP_VERSION}/cli/conf.d/probo.ini

# Set git info.
git config --global user.name "ProboCI"
git config --global user.email "noreply@probo.ci"

export DISPLAY=:99.0

set +v
