version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $BUILD_DIR/vendor/bin
    BLT_DIR: $BUILD_DIR/vendor/acquia/blt

events:
  build:
    steps:
        # Install global packages and set global configuration.
        - setup-environment:
            type: script
            script:
              - ${BLT_DIR}/scripts/pipelines/setup_environment

        # Install project level packages and set project level configuration.
        - setup-project:
            type: script
            script:
              - ${BLT_DIR}/scripts/pipelines/setup_project

        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - composer require drupal/acsf:^1.33.0
              - ${BLT_DIR}/scripts/pipelines/run_tests

        # Generate artifact.
        - build-artifact:
            type: script
            script:
            - ${BLT_DIR}/scripts/pipelines/build_artifact
