#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:${PATH}

yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'

blt validate:all
blt ci:setup -Dcreate_alias=false
blt tests:all -D behat.run-server=true -D behat.launch-selenium=false -D behat.launch-phantomjs=true -D behat.tags='~experimental' --yes -v --ansi

set +v
