#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:$PATH

# Set git info.
git config --global user.name "Acquia Cloud"
git config --global user.email "noreply@acquia.com"

# Create MySQL DB.
mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"

# Setup NVM.
nvm install v8.1.4
npm install -g npm

# The local.hostname is set to 0.0.0.0:8888 to run drush runserver on all
# available network interfaces.
yaml-cli update:value blt/blt.yml project.local.hostname '0.0.0.0:8888'

set +v
