#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:$PATH

# Set git info.
git config --global user.name "Acquia Cloud"
git config --global user.email "noreply@acquia.com"

# Create MySQL DB.
mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"

# Setup NVM.
nvm install v8.1.4
npm install -g npm

#  The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to test the site.
yaml-cli update:value blt/blt.yml project.local.hostname '127.0.0.1:8888'

set +v
