#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:$PATH

# Set git info.
git config --global user.name "Acquia Cloud"
git config --global user.email "noreply@acquia.com"

# Create MySQL DB.
sudo /etc/init.d/mysql start
mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"

set +v
