#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:${PATH}

blt tests:all --define drush.alias='${drush.aliases.ci}' --environment=ci -D behat.web-driver=chrome --no-interaction --ansi --verbose

set +v
