#!/usr/bin/env bash
# This file is managed by Composer and should not be modified by end users. To
# override its default behavior, copy it into your project and modify
# acquia-pipelines.yaml to call your custom version.

set -ev

export PATH=${COMPOSER_BIN}:${PATH}

blt validate --define drush.alias='${drush.aliases.ci}' --ansi --verbose

set +v
