#!/usr/bin/env bash

set -ev

if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)'
then
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]
  then
    echo "Only docs were updated, stopping build process."
    exit 0
  fi
fi

set +v
