#!/usr/bin/env bash

set -ev

# Load composer dependencies.
composer validate --no-check-all --ansi
composer install
# Install proper version of node for front end tasks.
source $NVM_DIR/nvm.sh
nvm install 4.4.1
nvm use 4.4.1
# Installs chromedriver to vendor/bin.
$BLT_DIR/scripts/linux/install-chrome.sh $COMPOSER_BIN
