#!/usr/bin/env bash

# Ordinarily we'd use set -e here but that breaks travis_wait, so we use exit
# pattern below.

set -v

blt validate:all --no-interaction || exit 1
travis_wait blt setup --define drush.alias='${drush.aliases.ci}' --environment=ci --no-interaction --verbose || exit 1
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --environment=ci --no-interaction --verbose || exit 1

set +v
