#!/usr/bin/env bash

set -ev

source ${BLT_DIR}/scripts/blt/ci/shared/run_tests

# Build codebase, validate, install Drupal, run basic tests.
mv ${BLT_DIR}/scripts/blt/ci/internal/config_split.config_split.ci.yml config/default/
drush en config_split --root=docroot -y
blt ci:build:validate:test -Dcreate_alias=false -Dbehat.run-server=true -Dblt.verbose=true
drush config-export --root=docroot -y
blt setup:config-import
drush pm-uninstall config_split --root=docroot -y

# Test core-only config management.
yaml-cli update:value blt/project.yml cm.strategy core-only
drush config-export --root=docroot -y
blt setup:config-import

# Test features config management.
yaml-cli update:value blt/project.yml cm.strategy features
drush config-export --root=docroot -y
blt setup:config-import

set +v
