#!/usr/bin/env bash

set -ev

# The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to run the site on Travis CI.
yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'

# Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
# sudo apt-get install xvfb
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start

# Execute tests.
blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test -Dblt.verbose=true
