name: ORCA CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORCA_SUT_NAME: acquia/blt
      ORCA_SUT_BRANCH: main
      ORCA_VERSION: ^3
      ORCA_PHPCS_STANDARD: AcquiaDrupalStrict
      BLT_PRINT_COMMAND_OUTPUT: 1
    strategy:
      matrix:
        include:
          - name: "Static code analysis"
            orca-job: "STATIC_CODE_ANALYSIS"
          - name: "Integrated test on previous minor Drupal core version"
            orca-job: "INTEGRATED_TEST_ON_PREVIOUS_MINOR"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Before install
        env:
          ORCA_JOB: ${{ matrix.orca-job }}
        run: |
          composer create-project --no-dev --ignore-platform-req=php acquia/orca ../orca "$ORCA_VERSION"
          curl https://patch-diff.githubusercontent.com/raw/acquia/orca/pull/151.patch | git -C ../orca apply
          ../orca/bin/travis/before_install.sh
      - name: Install
        env:
          ORCA_JOB: ${{ matrix.orca-job }}
        run: ../orca/bin/travis/install.sh
