name: ORCA CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    env:
      ORCA_SUT_NAME: acquia/blt
      ORCA_SUT_BRANCH: main
      ORCA_VERSION: ^3
      ORCA_PHPCS_STANDARD: AcquiaDrupalStrict
      BLT_PRINT_COMMAND_OUTPUT: 1
      ORCA_JOB: ${{ matrix.orca-job }}
    strategy:
      matrix:
        orca-job:
          - STATIC_CODE_ANALYSIS
          - INTEGRATED_TEST_ON_OLDEST_SUPPORTED
          - INTEGRATED_TEST_ON_PREVIOUS_MINOR
          - INTEGRATED_UPGRADE_TEST_FROM_PREVIOUS_MINOR
          - ISOLATED_TEST_ON_CURRENT
          - INTEGRATED_TEST_ON_CURRENT
          - INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR
          - ISOLATED_TEST_ON_CURRENT_DEV
          - INTEGRATED_TEST_ON_CURRENT_DEV
          - STRICT_DEPRECATED_CODE_SCAN
          - ISOLATED_TEST_ON_NEXT_MINOR
          - INTEGRATED_TEST_ON_NEXT_MINOR
          - ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_BETA_OR_LATER
        php-version: [ "7.3" ]
        allow-failure: [ false ]
        include:
          - orca-job: ISOLATED_TEST_ON_CURRENT
            php-version: "8.0"
            allow-failure: false

          - orca-job: INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR_DEV
            php-version: "7.3"
            allow-failure: true

          - orca-job: LOOSE_DEPRECATED_CODE_SCAN
            php-version: "7.3"
            allow-failure: true

          - orca-job: DEPRECATED_CODE_SCAN_W_CONTRIB
            php-version: "7.3"
            allow-failure: true

          - orca-job: ISOLATED_TEST_ON_NEXT_MINOR_DEV
            php-version: "7.3"
            allow-failure: true

          - orca-job: INTEGRATED_TEST_ON_NEXT_MINOR_DEV
            php-version: "7.3"
            allow-failure: true

          - orca-job: ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_DEV
            php-version: "7.3"
            allow-failure: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug2

      - name: Before install
        run: |
          git clone https://github.com/danepowell/orca.git ../orca
          git -C ../orca checkout ORCA-189
          composer install -d ../orca --no-dev --ignore-platform-req=php
          # composer create-project --no-dev --ignore-platform-req=php acquia/orca ../orca "$ORCA_VERSION"
          ../orca/bin/common/before_install.sh

      - name: Install
        run: ../orca/bin/common/install.sh

      - name: Before script
        run: ../orca/bin/common/before_script.sh

      - name: Script
        run: ../orca/bin/common/script.sh

      - name: After script
        run: ../orca/bin/common/after_script.sh

      - name: After success
        if: ${{ success() }}
        run: ../orca/bin/common/after_success.sh

      - name: After failure
        if: ${{ failure() }}
        run: ../orca/bin/common/after_failure.sh
